### ISSUE TITLE
Associated value doesn't expire with the Lock on etcdv3

### ISSUE THREAD

**Issue by Gaboose** [abronan/valkeyrie#31]
## Steps to reproduce:

1. Call `Lock(nil)` on `store.Locker`:
```go
kv, _ := valkeyrie.NewStore(store.ETCDV3, ...)
lock, _ := kv.NewLock("testLockTTL", &store.LockOptions{
	Value: []byte{"bar"},
	TTL:   time.Second
})
lock.Lock(nil)
select{}
```
2. Notice that two values appear on the etcd server:
```
testLockTTL: bar   
testLockTTL___lock/694d6dae7f833e5c: <empty>
```
3. Close the process with `CTRL+C` or replace `select{}` with `lock.Unlock()`

## Expected:
Both values expire after at most one second

## Actual:
`testLockTTL___lock/694d6dae7f833e5c` key expires, but `testLockTTL: bar` lingers forever.

Not sure if this was intended, but to me it seems pretty reasonable that the associated value would expire along with the lock.

**Comment by abronan** [comment]
The default behavior should clearly be that the key doesn't disappear when it is unlocked. That was the issue Traefik was seeing because it was inconsistent as opposed to Consul and Zookeeper (which kept the key around).

We need to include this as an option on `LockOptions` such that one could pass `DeleteKeyOnUnlock` or something like that to explicitly delete the key on Unlock.

I guess it's fine if the behavior isn't consistent on the Option because we can align that later on for each for store one by one.
